services:
  rabbitmq:
    image: 'rabbitmq:3.11-management'
    ports:
      - 5672:5672

  consumer-a:
    build:
      context: './consumer'
      dockerfile: Dockerfile
    image: "consumer"
    environment:
      - DOCKER_COMPOSE=true
    depends_on: 
      - rabbitmq
    profiles:
      - clients
  consumer-b:
    build:
      context: './consumer'
      dockerfile: Dockerfile
    image: "consumer"
    environment:
      - DOCKER_COMPOSE=true
    depends_on: 
      - rabbitmq
    profiles:
      - clients
  consumer-c:
    build:
      context: './consumer'
      dockerfile: Dockerfile
    image: "consumer"
    environment:
      - DOCKER_COMPOSE=true
    depends_on: 
      - rabbitmq
    profiles:
      - clients
  producer:
    build:
      context: './producer'
      dockerfile: Dockerfile
    image: "producer"
    environment:
      - DOCKER_COMPOSE=true
    depends_on: 
      - rabbitmq
    profiles:
      - clients

