services:
  rabbitmq:
    image: 'rabbitmq:3.11-management'
    ports:
      - 5672:5672

  consumer:
    deploy: 
      replicas: 5
    build:
      context: '.'
      dockerfile: './consumer/Dockerfile'
    image: "consumer"
    environment:
      - DOCKER_COMPOSE=true
    depends_on: 
      - rabbitmq

  producer:
    build:
      context: '.'
      dockerfile: './producer/Dockerfile'
    image: "producer"
    environment:
      - DOCKER_COMPOSE=true
    depends_on: 
      - rabbitmq

